"use client";

import React from "react";
import { Trophy, Info, AlertTriangle, CheckCircle2, TrendingUp } from "lucide-react";

interface PredictionResultCardProps {
  score: number;
}

export const PredictionResultCard: React.FC<PredictionResultCardProps> = ({ score }) => {
  // Cap displayed percentage for visual progress bar between 0 and 100
  const clampedScore = Math.min(Math.max(score, 0), 100);

  // Interpretation helper
  const getInterpretation = (val: number) => {
    if (val >= 90) {
      return {
        label: "Excellent performance",
        color: "text-emerald-400",
        bgColor: "bg-emerald-500/10",
        borderColor: "border-emerald-500/30",
        barColor: "bg-emerald-500",
        icon: Trophy,
      };
    } else if (val >= 75) {
      return {
        label: "Very good performance",
        color: "text-blue-400",
        bgColor: "bg-blue-500/10",
        borderColor: "border-blue-500/30",
        barColor: "bg-blue-500",
        icon: CheckCircle2,
      };
    } else if (val >= 60) {
      return {
        label: "Good performance",
        color: "text-sky-400",
        bgColor: "bg-sky-500/10",
        borderColor: "border-sky-500/30",
        barColor: "bg-sky-500",
        icon: TrendingUp,
      };
    } else if (val >= 40) {
      return {
        label: "Needs improvement",
        color: "text-amber-400",
        bgColor: "bg-amber-500/10",
        borderColor: "border-amber-500/30",
        barColor: "bg-amber-500",
        icon: AlertTriangle,
      };
    } else {
      return {
        label: "Significant improvement recommended",
        color: "text-rose-400",
        bgColor: "bg-rose-500/10",
        borderColor: "border-rose-500/30",
        barColor: "bg-rose-500",
        icon: AlertTriangle,
      };
    }
  };

  const interpretation = getInterpretation(score);
  const StatusIcon = interpretation.icon;

  return (
    <div className="mt-8 pt-6 border-t border-slate-700/60 animate-fade-in">
      <div className={`p-6 rounded-2xl ${interpretation.bgColor} border ${interpretation.borderColor} transition-all`}>
        <div className="flex items-center justify-between mb-3">
          <span className="text-xs font-semibold uppercase tracking-wider text-slate-400 flex items-center gap-1.5">
            <Info className="w-3.5 h-3.5" />
            Predicted Final Score
          </span>

          <div className={`flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold ${interpretation.bgColor} ${interpretation.color} border ${interpretation.borderColor}`}>
            <StatusIcon className="w-3.5 h-3.5" />
            <span>{interpretation.label}</span>
          </div>
        </div>

        {/* Large Score Display */}
        <div className="flex items-baseline gap-2 my-2">
          <span className={`text-4xl sm:text-5xl font-black tracking-tight ${interpretation.color}`}>
            {score.toFixed(2)}
          </span>
          <span className="text-xl font-bold text-slate-400">/ 100</span>
        </div>

        {/* Visual Progress Bar */}
        <div className="w-full bg-slate-900/60 h-3 rounded-full overflow-hidden my-4 border border-slate-700/40">
          <div
            className={`h-full ${interpretation.barColor} transition-all duration-700 ease-out`}
            style={{ width: `${clampedScore}%` }}
          />
        </div>

        {/* Disclaimer / Notice */}
        <p className="text-xs text-slate-400 flex items-center gap-1.5">
          <span className="font-semibold text-slate-300">Model prediction:</span>
          This result is generated by a trained Linear Regression model based on input habits. Final grades may vary.
        </p>
      </div>
    </div>
  );
};
